import 'package:tilawa_quran/quran/domain/entites/surah_details.dart';
import 'package:tilawa_quran/utils/assets.dart';

List<SurahDetails> quranDetails = const [
  SurahDetails(
    id: 1,
    name: 'الفاتحة',
    transliteration: "Al-Fatihah",
    totalVerses: 7,
    type: "meccan",
    image: [
      Assets.imagesQuranImages1,
    ],
  ),
  SurahDetails(
    id: 2,
    name: 'البقرة',
    transliteration: "Al-Baqarah",
    totalVerses: 286,
    type: "medinan",
    image: [
      Assets.imagesQuranImages2,
      Assets.imagesQuranImages3,
      Assets.imagesQuranImages4,
      Assets.imagesQuranImages5,
      Assets.imagesQuranImages6,
      Assets.imagesQuranImages7,
      Assets.imagesQuranImages8,
      Assets.imagesQuranImages9,
      Assets.imagesQuranImages10,
      Assets.imagesQuranImages11,
      Assets.imagesQuranImages12,
      Assets.imagesQuranImages13,
      Assets.imagesQuranImages14,
      Assets.imagesQuranImages15,
      Assets.imagesQuranImages16,
      Assets.imagesQuranImages17,
      Assets.imagesQuranImages18,
      Assets.imagesQuranImages19,
      Assets.imagesQuranImages20,
      Assets.imagesQuranImages21,
      Assets.imagesQuranImages22,
      Assets.imagesQuranImages23,
      Assets.imagesQuranImages24,
      Assets.imagesQuranImages25,
      Assets.imagesQuranImages26,
      Assets.imagesQuranImages27,
      Assets.imagesQuranImages28,
      Assets.imagesQuranImages29,
      Assets.imagesQuranImages30,
      Assets.imagesQuranImages31,
      Assets.imagesQuranImages32,
      Assets.imagesQuranImages33,
      Assets.imagesQuranImages34,
      Assets.imagesQuranImages35,
      Assets.imagesQuranImages36,
      Assets.imagesQuranImages37,
      Assets.imagesQuranImages38,
      Assets.imagesQuranImages39,
      Assets.imagesQuranImages40,
      Assets.imagesQuranImages41,
      Assets.imagesQuranImages42,
      Assets.imagesQuranImages43,
      Assets.imagesQuranImages44,
      Assets.imagesQuranImages45,
      Assets.imagesQuranImages46,
      Assets.imagesQuranImages47,
      Assets.imagesQuranImages48,
      Assets.imagesQuranImages49,
    ],
  ),
  SurahDetails(
    id: 3,
    name: 'آل عمران',
    transliteration: "Al-Imran",
    totalVerses: 200,
    type: "medinan",
    image: [
      Assets.imagesQuranImages50,
      Assets.imagesQuranImages51,
      Assets.imagesQuranImages52,
      Assets.imagesQuranImages53,
      Assets.imagesQuranImages54,
      Assets.imagesQuranImages55,
      Assets.imagesQuranImages56,
      Assets.imagesQuranImages57,
      Assets.imagesQuranImages58,
      Assets.imagesQuranImages59,
      Assets.imagesQuranImages60,
      Assets.imagesQuranImages61,
      Assets.imagesQuranImages62,
      Assets.imagesQuranImages63,
      Assets.imagesQuranImages64,
      Assets.imagesQuranImages65,
      Assets.imagesQuranImages66,
      Assets.imagesQuranImages67,
      Assets.imagesQuranImages68,
      Assets.imagesQuranImages69,
      Assets.imagesQuranImages70,
      Assets.imagesQuranImages71,
      Assets.imagesQuranImages72,
      Assets.imagesQuranImages73,
      Assets.imagesQuranImages74,
      Assets.imagesQuranImages75,
      Assets.imagesQuranImages76,
    ],
  ),
  SurahDetails(
    id: 4,
    name: 'النساء',
    transliteration: "An-Nisa'",
    totalVerses: 176,
    type: "medinan",
    image: [
      Assets.imagesQuranImages77,
      Assets.imagesQuranImages78,
      Assets.imagesQuranImages79,
      Assets.imagesQuranImages80,
      Assets.imagesQuranImages81,
      Assets.imagesQuranImages82,
      Assets.imagesQuranImages83,
      Assets.imagesQuranImages84,
      Assets.imagesQuranImages85,
      Assets.imagesQuranImages86,
      Assets.imagesQuranImages87,
      Assets.imagesQuranImages88,
      Assets.imagesQuranImages89,
      Assets.imagesQuranImages90,
      Assets.imagesQuranImages91,
      Assets.imagesQuranImages92,
      Assets.imagesQuranImages93,
      Assets.imagesQuranImages94,
      Assets.imagesQuranImages95,
      Assets.imagesQuranImages96,
      Assets.imagesQuranImages97,
      Assets.imagesQuranImages98,
      Assets.imagesQuranImages99,
      Assets.imagesQuranImages100,
      Assets.imagesQuranImages101,
      Assets.imagesQuranImages102,
      Assets.imagesQuranImages103,
      Assets.imagesQuranImages104,
      Assets.imagesQuranImages105,
      Assets.imagesQuranImages106,
    ],
  ),
  SurahDetails(
    id: 5,
    name: 'المائدة',
    transliteration: "Al-Ma'idah",
    totalVerses: 120,
    type: "medinan",
    image: [
      Assets.imagesQuranImages106,
      Assets.imagesQuranImages107,
      Assets.imagesQuranImages108,
      Assets.imagesQuranImages109,
      Assets.imagesQuranImages110,
      Assets.imagesQuranImages111,
      Assets.imagesQuranImages112,
      Assets.imagesQuranImages113,
      Assets.imagesQuranImages114,
      Assets.imagesQuranImages115,
      Assets.imagesQuranImages116,
      Assets.imagesQuranImages117,
      Assets.imagesQuranImages118,
      Assets.imagesQuranImages119,
      Assets.imagesQuranImages120,
      Assets.imagesQuranImages121,
      Assets.imagesQuranImages122,
      Assets.imagesQuranImages123,
      Assets.imagesQuranImages124,
      Assets.imagesQuranImages125,
      Assets.imagesQuranImages126,
      Assets.imagesQuranImages127,
    ],
  ),
  SurahDetails(
    id: 6,
    name: 'الأنعام',
    transliteration: "Al-An'am",
    totalVerses: 165,
    type: "meccan",
    image: [
      Assets.imagesQuranImages128,
      Assets.imagesQuranImages129,
      Assets.imagesQuranImages130,
      Assets.imagesQuranImages131,
      Assets.imagesQuranImages132,
      Assets.imagesQuranImages133,
      Assets.imagesQuranImages134,
      Assets.imagesQuranImages135,
      Assets.imagesQuranImages136,
      Assets.imagesQuranImages137,
      Assets.imagesQuranImages138,
      Assets.imagesQuranImages139,
      Assets.imagesQuranImages140,
      Assets.imagesQuranImages141,
      Assets.imagesQuranImages142,
      Assets.imagesQuranImages143,
      Assets.imagesQuranImages144,
      Assets.imagesQuranImages145,
      Assets.imagesQuranImages146,
      Assets.imagesQuranImages147,
      Assets.imagesQuranImages148,
      Assets.imagesQuranImages149,
      Assets.imagesQuranImages150,
    ],
  ),
  SurahDetails(
    id: 7,
    name: 'الأعراف',
    transliteration: "Al-A'raf",
    totalVerses: 206,
    type: "meccan",
    image: [
      Assets.imagesQuranImages151,
      Assets.imagesQuranImages152,
      Assets.imagesQuranImages153,
      Assets.imagesQuranImages154,
      Assets.imagesQuranImages155,
      Assets.imagesQuranImages156,
      Assets.imagesQuranImages157,
      Assets.imagesQuranImages158,
      Assets.imagesQuranImages159,
      Assets.imagesQuranImages160,
      Assets.imagesQuranImages161,
      Assets.imagesQuranImages162,
      Assets.imagesQuranImages163,
      Assets.imagesQuranImages164,
      Assets.imagesQuranImages165,
      Assets.imagesQuranImages166,
      Assets.imagesQuranImages167,
      Assets.imagesQuranImages168,
      Assets.imagesQuranImages169,
      Assets.imagesQuranImages170,
      Assets.imagesQuranImages171,
      Assets.imagesQuranImages172,
      Assets.imagesQuranImages173,
      Assets.imagesQuranImages174,
      Assets.imagesQuranImages175,
      Assets.imagesQuranImages176,
    ],
  ),
  SurahDetails(
    id: 8,
    name: 'الأنفال',
    transliteration: "Al-Anfal",
    totalVerses: 75,
    type: "medinan",
    image: [
      Assets.imagesQuranImages177,
      Assets.imagesQuranImages178,
      Assets.imagesQuranImages179,
      Assets.imagesQuranImages180,
      Assets.imagesQuranImages181,
      Assets.imagesQuranImages182,
      Assets.imagesQuranImages183,
      Assets.imagesQuranImages184,
      Assets.imagesQuranImages185,
      Assets.imagesQuranImages186,
    ],
  ),
  SurahDetails(
    id: 9,
    name: 'التوبة',
    transliteration: "At-Tawbah",
    totalVerses: 129,
    type: "medinan",
    image: [
      Assets.imagesQuranImages187,
      Assets.imagesQuranImages188,
      Assets.imagesQuranImages189,
      Assets.imagesQuranImages190,
      Assets.imagesQuranImages191,
      Assets.imagesQuranImages192,
      Assets.imagesQuranImages193,
      Assets.imagesQuranImages194,
      Assets.imagesQuranImages195,
      Assets.imagesQuranImages196,
      Assets.imagesQuranImages197,
      Assets.imagesQuranImages198,
      Assets.imagesQuranImages199,
      Assets.imagesQuranImages200,
      Assets.imagesQuranImages201,
      Assets.imagesQuranImages202,
      Assets.imagesQuranImages203,
      Assets.imagesQuranImages204,
      Assets.imagesQuranImages205,
      Assets.imagesQuranImages206,
      Assets.imagesQuranImages207,
    ],
  ),
  SurahDetails(
    id: 10,
    name: 'يونس',
    transliteration: "Yunus",
    totalVerses: 109,
    type: "meccan",
    image: [
      Assets.imagesQuranImages208,
      Assets.imagesQuranImages209,
      Assets.imagesQuranImages210,
      Assets.imagesQuranImages211,
      Assets.imagesQuranImages212,
      Assets.imagesQuranImages213,
      Assets.imagesQuranImages214,
      Assets.imagesQuranImages215,
      Assets.imagesQuranImages216,
      Assets.imagesQuranImages217,
      Assets.imagesQuranImages218,
      Assets.imagesQuranImages219,
      Assets.imagesQuranImages220,
      Assets.imagesQuranImages221,
    ],
  ),
  SurahDetails(
    id: 11,
    name: 'هود',
    transliteration: "Hud",
    totalVerses: 123,
    type: "meccan",
    image: [
      Assets.imagesQuranImages221,
      Assets.imagesQuranImages222,
      Assets.imagesQuranImages223,
      Assets.imagesQuranImages224,
      Assets.imagesQuranImages225,
      Assets.imagesQuranImages226,
      Assets.imagesQuranImages227,
      Assets.imagesQuranImages228,
      Assets.imagesQuranImages229,
      Assets.imagesQuranImages230,
      Assets.imagesQuranImages231,
      Assets.imagesQuranImages232,
      Assets.imagesQuranImages233,
      Assets.imagesQuranImages234,
      Assets.imagesQuranImages235
    ],
  ),
  SurahDetails(
    id: 12,
    name: 'يوسف',
    transliteration: "Yusuf",
    totalVerses: 111,
    type: "meccan",
    image: [
      Assets.imagesQuranImages235,
      Assets.imagesQuranImages236,
      Assets.imagesQuranImages237,
      Assets.imagesQuranImages238,
      Assets.imagesQuranImages239,
      Assets.imagesQuranImages240,
      Assets.imagesQuranImages241,
      Assets.imagesQuranImages242,
      Assets.imagesQuranImages243,
      Assets.imagesQuranImages244,
      Assets.imagesQuranImages245,
      Assets.imagesQuranImages246,
      Assets.imagesQuranImages247,
      Assets.imagesQuranImages248,
    ],
  ),
  SurahDetails(
    id: 13,
    name: 'الرعد',
    transliteration: "Ar-Ra'd",
    totalVerses: 43,
    type: "medinan",
    image: [
      Assets.imagesQuranImages249,
      Assets.imagesQuranImages250,
      Assets.imagesQuranImages251,
      Assets.imagesQuranImages252,
      Assets.imagesQuranImages253,
      Assets.imagesQuranImages254,
      Assets.imagesQuranImages255
    ],
  ),
  SurahDetails(
    id: 14,
    name: 'إبراهيم',
    transliteration: "Ibrahim",
    totalVerses: 52,
    type: "meccan",
    image: [
      Assets.imagesQuranImages255,
      Assets.imagesQuranImages256,
      Assets.imagesQuranImages257,
      Assets.imagesQuranImages258,
      Assets.imagesQuranImages259,
      Assets.imagesQuranImages260,
      Assets.imagesQuranImages261,
    ],
  ),
  SurahDetails(
      id: 15,
      name: 'الحجر',
      transliteration: "Al-Hijr",
      totalVerses: 99,
      type: "meccan",
      image: [
        Assets.imagesQuranImages262,
        Assets.imagesQuranImages263,
        Assets.imagesQuranImages264,
        Assets.imagesQuranImages265,
        Assets.imagesQuranImages266,
        Assets.imagesQuranImages267
      ]),
  SurahDetails(
    id: 16,
    name: 'النحل',
    transliteration: "An-Nahl",
    totalVerses: 128,
    type: "meccan",
    image: [
      Assets.imagesQuranImages267,
Assets.imagesQuranImages268,
Assets.imagesQuranImages269,
Assets.imagesQuranImages270,
Assets.imagesQuranImages271,
Assets.imagesQuranImages272,
Assets.imagesQuranImages273,
Assets.imagesQuranImages274,
Assets.imagesQuranImages275,
Assets.imagesQuranImages276,
Assets.imagesQuranImages277,
Assets.imagesQuranImages278,
Assets.imagesQuranImages279,
Assets.imagesQuranImages280,
Assets.imagesQuranImages281
    ],
  ),
  SurahDetails(
    id: 17,
    name: 'الإسراء',
    transliteration: "Al-Isra",
    totalVerses: 111,
    type: "meccan",
    image: [
      Assets.imagesQuranImages282,
Assets.imagesQuranImages283,
Assets.imagesQuranImages284,
Assets.imagesQuranImages285,
Assets.imagesQuranImages286,
Assets.imagesQuranImages287,
Assets.imagesQuranImages288,
Assets.imagesQuranImages289,
Assets.imagesQuranImages290,
Assets.imagesQuranImages291,
Assets.imagesQuranImages292,
Assets.imagesQuranImages293
    ],
  ),
  SurahDetails(
    id: 18,
    name: 'الكهف',
    transliteration: "Al-Kahf",
    totalVerses: 110,
    type: "meccan",
    image: [
      Assets.imagesQuranImages293,
Assets.imagesQuranImages294,
Assets.imagesQuranImages295,
Assets.imagesQuranImages296,
Assets.imagesQuranImages297,
Assets.imagesQuranImages298,
Assets.imagesQuranImages299,
Assets.imagesQuranImages300,
Assets.imagesQuranImages301,
Assets.imagesQuranImages302,
Assets.imagesQuranImages303,
Assets.imagesQuranImages304
    ],
  ),
  SurahDetails(
    id: 19,
    name: 'مريم',
    transliteration: "Maryam",
    totalVerses: 98,
    type: "meccan",
    image: [Assets.imagesQuranImages305,
Assets.imagesQuranImages306,
Assets.imagesQuranImages307,
Assets.imagesQuranImages308,
Assets.imagesQuranImages309,
Assets.imagesQuranImages310,
Assets.imagesQuranImages311,
Assets.imagesQuranImages312],
  ),
  SurahDetails(
    id: 20,
    name: 'طه',
    transliteration: "Ta-Ha",
    totalVerses: 135,
    type: "meccan",
    image: [
      Assets.imagesQuranImages312,
Assets.imagesQuranImages313,
Assets.imagesQuranImages314,
Assets.imagesQuranImages315,
Assets.imagesQuranImages316,
Assets.imagesQuranImages317,
Assets.imagesQuranImages318,
Assets.imagesQuranImages319,
Assets.imagesQuranImages320,
Assets.imagesQuranImages321,
    ],
  ),
  SurahDetails(
    id: 21,
    name: 'الأنبياء',
    transliteration: "Al-Anbiya",
    totalVerses: 112,
    type: "meccan",
    image: [
      Assets.imagesQuranImages322,
Assets.imagesQuranImages323,
Assets.imagesQuranImages324,
Assets.imagesQuranImages325,
Assets.imagesQuranImages326,
Assets.imagesQuranImages327,
Assets.imagesQuranImages328,
Assets.imagesQuranImages329,
Assets.imagesQuranImages330,
Assets.imagesQuranImages331,
    ],
  ),
  SurahDetails(
    id: 22,
    name: 'الحج',
    transliteration: "Al-Hajj",
    totalVerses: 78,
    type: "medinan",
    image: [
      Assets.imagesQuranImages332,
Assets.imagesQuranImages333,
Assets.imagesQuranImages334,
Assets.imagesQuranImages335,
Assets.imagesQuranImages336,
Assets.imagesQuranImages337,
Assets.imagesQuranImages338,
Assets.imagesQuranImages339,
Assets.imagesQuranImages340,
Assets.imagesQuranImages341,
    ],
  ),
  SurahDetails(
    id: 23,
    name: 'المؤمنون',
    transliteration: "Al-Mu'minun",
    totalVerses: 118,
    type: "meccan",
    image: [Assets.imagesQuranImages342,
Assets.imagesQuranImages343,
Assets.imagesQuranImages344,
Assets.imagesQuranImages345,
Assets.imagesQuranImages346,
Assets.imagesQuranImages347,
Assets.imagesQuranImages348,
Assets.imagesQuranImages349,],
  ),
  SurahDetails(
    id: 24,
    name: 'النور',
    transliteration: "An-Nur",
    totalVerses: 64,
    type: "medinan",
    image: [
Assets.imagesQuranImages350,
Assets.imagesQuranImages351,
Assets.imagesQuranImages352,
Assets.imagesQuranImages353,
Assets.imagesQuranImages354,
Assets.imagesQuranImages355,
Assets.imagesQuranImages356,
Assets.imagesQuranImages357,
Assets.imagesQuranImages358,
Assets.imagesQuranImages359      

    ],
  ),
  SurahDetails(
    id: 25,
    name: 'الفرقان',
    transliteration: "Al-Furqan",
    totalVerses: 77,
    type: "meccan",
    image: [
      Assets.imagesQuranImages359,
Assets.imagesQuranImages360,
Assets.imagesQuranImages361,
Assets.imagesQuranImages362,
Assets.imagesQuranImages363,
Assets.imagesQuranImages364,
Assets.imagesQuranImages365,
Assets.imagesQuranImages366,

    ],
  ),
  SurahDetails(
    id: 26,
    name: 'الشعراء',
    transliteration: "Ash-Shu'ara",
    totalVerses: 227,
    type: "meccan",
    image: [
      Assets.imagesQuranImages367,
Assets.imagesQuranImages368,
Assets.imagesQuranImages369,
Assets.imagesQuranImages370,
Assets.imagesQuranImages371,
Assets.imagesQuranImages372,
Assets.imagesQuranImages373,
Assets.imagesQuranImages374,
Assets.imagesQuranImages375,
Assets.imagesQuranImages376,
    ],
  ),
  SurahDetails(
    id: 27,
    name: 'النمل',
    transliteration: "An-Naml",
    totalVerses: 93,
    type: "meccan",
    image: [
      Assets.imagesQuranImages377,
Assets.imagesQuranImages378,
Assets.imagesQuranImages379,
Assets.imagesQuranImages380,
Assets.imagesQuranImages381,
Assets.imagesQuranImages382,
Assets.imagesQuranImages383,
Assets.imagesQuranImages384,
Assets.imagesQuranImages385
    ],
  ),
  SurahDetails(
    id: 28,
    name: 'القصص',
    transliteration: "Al-Qasas",
    totalVerses: 88,
    type: "meccan",
    image: [
      Assets.imagesQuranImages385,
Assets.imagesQuranImages386,
Assets.imagesQuranImages387,
Assets.imagesQuranImages388,
Assets.imagesQuranImages389,
Assets.imagesQuranImages390,
Assets.imagesQuranImages391,
Assets.imagesQuranImages392,
Assets.imagesQuranImages393,
Assets.imagesQuranImages394,
Assets.imagesQuranImages395,
Assets.imagesQuranImages396
    ],
  ),
  SurahDetails(
    id: 29,
    name: 'العنكبوت',
    transliteration: "Al-Ankabut",
    totalVerses: 69,
    type: "meccan",
    image: [
      Assets.imagesQuranImages385,
Assets.imagesQuranImages386,
Assets.imagesQuranImages387,
Assets.imagesQuranImages388,
Assets.imagesQuranImages389,
Assets.imagesQuranImages390,
Assets.imagesQuranImages391,
Assets.imagesQuranImages392,
Assets.imagesQuranImages393,
Assets.imagesQuranImages394,
Assets.imagesQuranImages395,
Assets.imagesQuranImages396
    ],
  ),
  SurahDetails(
    id: 30,
    name: 'الروم',
    transliteration: "Ar-Rum",
    totalVerses: 60,
    type: "meccan",
    image: [
      Assets.imagesQuranImages404,
Assets.imagesQuranImages405,
Assets.imagesQuranImages406,
Assets.imagesQuranImages407,
Assets.imagesQuranImages408,
Assets.imagesQuranImages409,
Assets.imagesQuranImages410,
    ],
  ),
  SurahDetails(
    id: 31,
    name: 'لقمان',
    transliteration: "Luqman",
    totalVerses: 34,
    type: "meccan",
    image: [
      Assets.imagesQuranImages411,
Assets.imagesQuranImages412,
Assets.imagesQuranImages413,
Assets.imagesQuranImages414,

    ],
  ),
  SurahDetails(
    id: 32,
    name: 'السجدة',
    transliteration: "As-Sajda",
    totalVerses: 30,
    type: "meccan",
    image: [
      Assets.imagesQuranImages415,
Assets.imagesQuranImages416,
Assets.imagesQuranImages417
    ],
  ),
  SurahDetails(
    id: 33,
    name: 'الأحزاب',
    transliteration: "Al-Ahzab",
    totalVerses: 73,
    type: "medinan",
    image: [
      Assets.imagesQuranImages418,
Assets.imagesQuranImages419,
Assets.imagesQuranImages420,
Assets.imagesQuranImages421,
Assets.imagesQuranImages422,
Assets.imagesQuranImages423,
Assets.imagesQuranImages424,
Assets.imagesQuranImages425,
Assets.imagesQuranImages426,
Assets.imagesQuranImages427,

    ],
  ),
  SurahDetails(
    id: 34,
    name: 'سبأ',
    transliteration: "Saba",
    totalVerses: 54,
    type: "meccan",
    image: [Assets.imagesQuranImages428,
Assets.imagesQuranImages429,
Assets.imagesQuranImages430,
Assets.imagesQuranImages431,
Assets.imagesQuranImages432,
Assets.imagesQuranImages433,
Assets.imagesQuranImages434],
  ),
  SurahDetails(
    id: 35,
    name: 'فاطر',
    transliteration: "Fatir",
    totalVerses: 45,
    type: "meccan",
    image: [Assets.imagesQuranImages434,
Assets.imagesQuranImages435,
Assets.imagesQuranImages436,
Assets.imagesQuranImages437,
Assets.imagesQuranImages438,
Assets.imagesQuranImages439,
Assets.imagesQuranImages440,
],
  ),
  SurahDetails(
    id: 36,
    name: 'يس',
    transliteration: "Ya-Sin",
    totalVerses: 83,
    type: "meccan",
    image: [
      Assets.imagesQuranImages440,
Assets.imagesQuranImages441,
Assets.imagesQuranImages442,
Assets.imagesQuranImages443,
Assets.imagesQuranImages444,
Assets.imagesQuranImages445,
    ],
  ),
  SurahDetails(
    id: 37,
    name: 'الصافات',
    transliteration: "As-Saffat",
    totalVerses: 182,
    type: "meccan",
    image: [
      Assets.imagesQuranImages446,
Assets.imagesQuranImages447,
Assets.imagesQuranImages448,
Assets.imagesQuranImages449,
Assets.imagesQuranImages450,
Assets.imagesQuranImages451,
Assets.imagesQuranImages452,
Assets.imagesQuranImages453,

    ],
  ),
  SurahDetails(
    id: 38,
    name: 'ص',
    transliteration: "Sad",
    totalVerses: 88,
    type: "meccan",
    image: [Assets.imagesQuranImages453,
Assets.imagesQuranImages454,
Assets.imagesQuranImages455,
Assets.imagesQuranImages456,
Assets.imagesQuranImages457,
Assets.imagesQuranImages458,




],
  ),
  SurahDetails(
    id: 39,
    name: 'الزمر',
    transliteration: "Az-Zumar",
    totalVerses: 75,
    type: "meccan",
    image: [
      Assets.imagesQuranImages458,
Assets.imagesQuranImages459,
Assets.imagesQuranImages460,
Assets.imagesQuranImages461,
Assets.imagesQuranImages462,
Assets.imagesQuranImages463,
Assets.imagesQuranImages464,
Assets.imagesQuranImages465,
Assets.imagesQuranImages466,
Assets.imagesQuranImages467,

    ],
  ),
  SurahDetails(
    id: 40,
    name: 'غافر',
    transliteration: "Ghafir",
    totalVerses: 85,
    type: "meccan",
    image: [Assets.imagesQuranImages467,
Assets.imagesQuranImages468,
Assets.imagesQuranImages469,
Assets.imagesQuranImages470,
Assets.imagesQuranImages471,
Assets.imagesQuranImages472,
Assets.imagesQuranImages473,
Assets.imagesQuranImages474,
Assets.imagesQuranImages475,
Assets.imagesQuranImages476,
],
  ),
  SurahDetails(
    id: 41,
    name: 'فصلت',
    transliteration: "Fussilat",
    totalVerses: 54,
    type: "meccan",
    image: [

      Assets.imagesQuranImages477,
Assets.imagesQuranImages478,
Assets.imagesQuranImages479,
Assets.imagesQuranImages480,
Assets.imagesQuranImages481,
Assets.imagesQuranImages482,

    ],
  ),
  SurahDetails(
    id: 42,
    name: 'الشورى',
    transliteration: "Ash-Shura",
    totalVerses: 53,
    type: "meccan",
    image: [
      Assets.imagesQuranImages483,
Assets.imagesQuranImages484,
Assets.imagesQuranImages485,
Assets.imagesQuranImages486,
Assets.imagesQuranImages487,
Assets.imagesQuranImages488,
Assets.imagesQuranImages489,

    ],
  ),
  SurahDetails(
    id: 43,
    name: 'الزخرف',
    transliteration: "Az-Zukhruf",
    totalVerses: 89,
    type: "meccan",
    image: [
      Assets.imagesQuranImages489,
Assets.imagesQuranImages490,
Assets.imagesQuranImages491,
Assets.imagesQuranImages492,
Assets.imagesQuranImages493,
Assets.imagesQuranImages494,
Assets.imagesQuranImages495,

    ],
  ),
  SurahDetails(
    id: 44,
    name: 'الدخان',
    transliteration: "Ad-Dukhan",
    totalVerses: 59,
    type: "meccan",
    image: [

      Assets.imagesQuranImages496,
Assets.imagesQuranImages497,
Assets.imagesQuranImages498,

    ],
  ),
  SurahDetails(
    id: 45,
    name: 'الجاثية',
    transliteration: "Al-Jathiyah",
    totalVerses: 37,
    type: "meccan",
    image: [

      Assets.imagesQuranImages499,
Assets.imagesQuranImages500,
Assets.imagesQuranImages501,
  Assets.imagesQuranImages502,

    ],
  ),
  SurahDetails(
    id: 46,
    name: 'الأحقاف',
    transliteration: "Al-Ahqaf",
    totalVerses: 35,
    type: "meccan",
    image: [
        Assets.imagesQuranImages502,
Assets.imagesQuranImages503,
Assets.imagesQuranImages504,
Assets.imagesQuranImages505,
Assets.imagesQuranImages506,
    ],
  ),
  SurahDetails(
    id: 47,
    name: 'محمد',
    transliteration: "Muhammad",
    totalVerses: 38,
    type: "medinan",
    image: [

      Assets.imagesQuranImages507,
Assets.imagesQuranImages508,
Assets.imagesQuranImages509,
Assets.imagesQuranImages510,

    ],
  ),
  SurahDetails(
    id: 48,
    name: 'الفتح',
    transliteration: "Al-Fath",
    totalVerses: 29,
    type: "medinan",
    image: [
      
Assets.imagesQuranImages511,
Assets.imagesQuranImages512,
Assets.imagesQuranImages513,
Assets.imagesQuranImages514,
Assets.imagesQuranImages515,


    ],
  ),
  SurahDetails(
    id: 49,
    name: 'الحجرات',
    transliteration: "Al-Hujurat",
    totalVerses: 18,
    type: "medinan",
    image: [
Assets.imagesQuranImages515,

      Assets.imagesQuranImages516,
Assets.imagesQuranImages517,
    ],
  ),
  SurahDetails(
    id: 50,
    name: 'ق',
    transliteration: "Qaf",
    totalVerses: 45,
    type: "meccan",
    image: [

      Assets.imagesQuranImages518,
Assets.imagesQuranImages519,
Assets.imagesQuranImages520,
    ],
  ),
  SurahDetails(
    id: 51,
    name: 'الذاريات',
    transliteration: "Adh-Dhariyat",
    totalVerses: 60,
    type: "meccan",
    image: [
Assets.imagesQuranImages520,

      Assets.imagesQuranImages521,
Assets.imagesQuranImages522,
Assets.imagesQuranImages523,
    ],
  ),
  SurahDetails(
    id: 52,
    name: 'الطور',
    transliteration: "At-Tur",
    totalVerses: 49,
    type: "meccan",
    image: [
Assets.imagesQuranImages523,

      Assets.imagesQuranImages524,
Assets.imagesQuranImages525,
    ],
  ),
  SurahDetails(
    id: 53,
    name: 'النجم',
    transliteration: "An-Najm",
    totalVerses: 62,
    type: "meccan",
    image: [

      Assets.imagesQuranImages526,
Assets.imagesQuranImages527,
Assets.imagesQuranImages528,
    ],
  ),
  SurahDetails(
    id: 54,
    name: 'القمر',
    transliteration: "Al-Qamar",
    totalVerses: 55,
    type: "meccan",
    image: [
Assets.imagesQuranImages528,

      Assets.imagesQuranImages529,
Assets.imagesQuranImages530,
Assets.imagesQuranImages531,

    ],
  ),
  SurahDetails(
    id: 55,
    name: 'الرحمن',
    transliteration: "Ar-Rahman",
    totalVerses: 78,
    type: "medinan",
    image: [
Assets.imagesQuranImages531,

      Assets.imagesQuranImages532,
Assets.imagesQuranImages533,
Assets.imagesQuranImages534
    ],
  ),
  SurahDetails(
    id: 56,
    name: 'الواقعة',
    transliteration: "Al-Waqi'ah",
    totalVerses: 96,
    type: "meccan",
    image: [
Assets.imagesQuranImages534,
      Assets.imagesQuranImages535,
Assets.imagesQuranImages536,
Assets.imagesQuranImages537,
    ],
  ),
  SurahDetails(
    id: 57,
    name: 'الحديد',
    transliteration: "Al-Hadid",
    totalVerses: 29,
    type: "medinan",
    image: [
Assets.imagesQuranImages537,

      Assets.imagesQuranImages538,
Assets.imagesQuranImages539,
Assets.imagesQuranImages540,
Assets.imagesQuranImages541,
    ],
  ),
  SurahDetails(
    id: 58,
    name: 'المجادلة',
    transliteration: "Al-Mujadila",
    totalVerses: 22,
    type: "medinan",
    image: [

      Assets.imagesQuranImages542,
Assets.imagesQuranImages543,
Assets.imagesQuranImages544,
Assets.imagesQuranImages545,

    ],
  ),
  SurahDetails(
    id: 59,
    name: 'الحشر',
    transliteration: "Al-Hashr",
    totalVerses: 24,
    type: "medinan",
    image: [
Assets.imagesQuranImages545,
Assets.imagesQuranImages546,

      Assets.imagesQuranImages547,
Assets.imagesQuranImages548,

    ],
  ),
  SurahDetails(
    id: 60,
    name: 'الممتحنة',
    transliteration: "Al-Mumtahina",
    totalVerses: 13,
    type: "medinan",
    image: [

      Assets.imagesQuranImages549,
Assets.imagesQuranImages550,

      Assets.imagesQuranImages551,
    ],
  ),
  SurahDetails(
    id: 61,
    name: 'الصف',
    transliteration: "As-Saff",
    totalVerses: 14,
    type: "medinan",
    image: [
      Assets.imagesQuranImages551,

      Assets.imagesQuranImages552,
    ],
  ),
  SurahDetails(
    id: 62,
    name: 'الجمعة',
    transliteration: "Al-Jumu'ah",
    totalVerses: 11,
    type: "medinan",
    image: [

      Assets.imagesQuranImages553,

      Assets.imagesQuranImages554,
    ],
  ),
  SurahDetails(
    id: 63,
    name: 'المنافقون',
    transliteration: "Al-Munafiqun",
    totalVerses: 11,
    type: "medinan",
    image: [
      Assets.imagesQuranImages554,

      Assets.imagesQuranImages555,
    ],
  ),
  SurahDetails(
    id: 64,
    name: 'التغابن',
    transliteration: "At-Taghabun",
    totalVerses: 18,
    type: "medinan",
    image: [

      Assets.imagesQuranImages556,
      Assets.imagesQuranImages557,

    ],
  ),
  SurahDetails(
    id: 65,
    name: 'الطلاق',
    transliteration: "At-Talaq",
    totalVerses: 12,
    type: "medinan",
    image: [

      Assets.imagesQuranImages558,

      Assets.imagesQuranImages559,
    ],
  ),
  SurahDetails(
    id: 66,
    name: 'التحريم',
    transliteration: "At-Tahrim",
    totalVerses: 12,
    type: "medinan",
    image: [

      Assets.imagesQuranImages560,

      Assets.imagesQuranImages561,
    ],
  ),
  SurahDetails(
    id: 67,
    name: 'الملك',
    transliteration: "Al-Mulk",
    totalVerses: 30,
    type: "meccan",
    image: [

      Assets.imagesQuranImages562,

      Assets.imagesQuranImages563,

      Assets.imagesQuranImages564,
    ],
  ),
  SurahDetails(
    id: 68,
    name: 'القلم',
    transliteration: "Al-Qalam",
    totalVerses: 52,
    type: "meccan",
    image: [
      Assets.imagesQuranImages564,

      Assets.imagesQuranImages565,

      Assets.imagesQuranImages566,
    ],
  ),
  SurahDetails(
    id: 69,
    name: 'الحاقة',
    transliteration: "Al-Haaqqa",
    totalVerses: 52,
    type: "meccan",
    image: [
      Assets.imagesQuranImages566,

      Assets.imagesQuranImages567,

      Assets.imagesQuranImages568,
    ],
  ),
  SurahDetails(
    id: 70,
    name: 'المعارج',
    transliteration: "Al-Ma'arij",
    totalVerses: 44,
    type: "meccan",
    image: [
      Assets.imagesQuranImages568,

      Assets.imagesQuranImages569,

      Assets.imagesQuranImages570,

    ],
  ),
  SurahDetails(
    id: 71,
    name: 'نوح',
    transliteration: "Nuh",
    totalVerses: 28,
    type: "meccan",
    image: [
      Assets.imagesQuranImages570,

      Assets.imagesQuranImages571,
    ],
  ),
  SurahDetails(
    id: 72,
    name: 'الجن',
    transliteration: "Al-Jinn",
    totalVerses: 28,
    type: "meccan",
    image: [

      Assets.imagesQuranImages572,

      Assets.imagesQuranImages573,
    ],
  ),
  SurahDetails(
    id: 73,
    name: 'المزمل',
    transliteration: "Al-Muzzammil",
    totalVerses: 20,
    type: "meccan",
    image: [

      Assets.imagesQuranImages574,

      Assets.imagesQuranImages575,
    ],
  ),
  SurahDetails(
    id: 74,
    name: 'المدثر',
    transliteration: "Al-Muddathir",
    totalVerses: 56,
    type: "meccan",
    image: [
      Assets.imagesQuranImages575,

      Assets.imagesQuranImages576,

      Assets.imagesQuranImages577,
    ],
  ),
  SurahDetails(
    id: 75,
    name: 'القيامة',
    transliteration: "Al-Qiyama",
    totalVerses: 40,
    type: "meccan",
    image: [
      Assets.imagesQuranImages577,

      Assets.imagesQuranImages578,
    ],
  ),
  SurahDetails(
    id: 76,
    name: 'الإنسان',
    transliteration: "Al-Insan",
    totalVerses: 31,
    type: "medinan",
    image: [
      Assets.imagesQuranImages578,

      Assets.imagesQuranImages579,

      Assets.imagesQuranImages580,

    ],
  ),
  SurahDetails(
    id: 77,
    name: 'المرسلات',
    transliteration: "Al-Mursalat",
    totalVerses: 50,
    type: "meccan",
    image: [

      Assets.imagesQuranImages580,

      Assets.imagesQuranImages581,
    ],
  ),
  SurahDetails(
    id: 78,
    name: 'النبأ',
    transliteration: "An-Naba",
    totalVerses: 40,
    type: "meccan",
    image: [

      Assets.imagesQuranImages582,

      Assets.imagesQuranImages583,
    ],
  ),
  SurahDetails(
    id: 79,
    name: 'النازعات',
    transliteration: "An-Nazi'at",
    totalVerses: 46,
    type: "meccan",
    image: [
      Assets.imagesQuranImages583,

      Assets.imagesQuranImages584,
    ],
  ),
  SurahDetails(
    id: 80,
    name: 'عبس',
    transliteration: "Abasa",
    totalVerses: 42,
    type: "meccan",
    image: [],
  ),
  SurahDetails(
    id: 81,
    name: 'التكوير',
    transliteration: "At-Takwir",
    totalVerses: 29,
    type: "meccan",
    image: [

      Assets.imagesQuranImages585,
    ],
  ),
  SurahDetails(
    id: 82,
    name: 'الإنفطار',
    transliteration: "Al-Infitar",
    totalVerses: 19,
    type: "meccan",
    image: [

      Assets.imagesQuranImages586,
    ],
  ),
  SurahDetails(
    id: 83,
    name: 'المطففين',
    transliteration: "Al-Mutaffifin",
    totalVerses: 36,
    type: "meccan",
    image: [

      Assets.imagesQuranImages587,
    ],
  ),
  SurahDetails(
    id: 84,
    name: 'الإنشقاق',
    transliteration: "Al-Inshiqaq",
    totalVerses: 25,
    type: "meccan",
    image: [
      Assets.imagesQuranImages587,

      Assets.imagesQuranImages588,
      Assets.imagesQuranImages589,

    ],
  ),
  SurahDetails(
    id: 85,
    name: 'البروج',
    transliteration: "Al-Buruj",
    totalVerses: 22,
    type: "meccan",
    image: [
      Assets.imagesQuranImages589,

    ],
  ),
  SurahDetails(
    id: 86,
    name: 'الطارق',
    transliteration: "At-Tariq",
    totalVerses: 17,
    type: "meccan",
    image: [

      Assets.imagesQuranImages590,
    ],
  ),
  SurahDetails(
    id: 87,
    name: 'الأعلى',
    transliteration: "Al-Ala",
    totalVerses: 19,
    type: "meccan",
    image: [

      Assets.imagesQuranImages591,
    ],
  ),
  SurahDetails(
    id: 88,
    name: 'الغاشية',
    transliteration: "Al-Ghashiyah",
    totalVerses: 26,
    type: "meccan",
    image: [
      Assets.imagesQuranImages591,

      Assets.imagesQuranImages592,
    ],
  ),
  SurahDetails(
    id: 89,
    name: 'الفجر',
    transliteration: "Al-Fajr",
    totalVerses: 30,
    type: "meccan",
    image: [
      Assets.imagesQuranImages593,

      Assets.imagesQuranImages594,

    ],
  ),
  SurahDetails(
    id: 90,
    name: 'البلد',
    transliteration: "Al-Balad",
    totalVerses: 20,
    type: "meccan",
    image: [
      Assets.imagesQuranImages594,

    ],
  ),
  SurahDetails(
    id: 91,
    name: 'الشمس',
    transliteration: "Ash-Shams",
    totalVerses: 15,
    type: "meccan",
    image: [

      Assets.imagesQuranImages595,
    ],
  ),
  SurahDetails(
    id: 92,
    name: 'الليل',
    transliteration: "Al-Layl",
    totalVerses: 21,
    type: "meccan",
    image: [
      Assets.imagesQuranImages595,

      Assets.imagesQuranImages596,
    ],
  ),
  SurahDetails(
    id: 93,
    name: 'الضحى',
    transliteration: "Ad-Duha",
    totalVerses: 11,
    type: "meccan",
    image: [
      Assets.imagesQuranImages596,

    ],
  ),
  SurahDetails(
    id: 94,
    name: 'الشرح',
    transliteration: "Ash-Sharh",
    totalVerses: 8,
    type: "meccan",
    image: [
      Assets.imagesQuranImages596,

    ],
  ),
  SurahDetails(
    id: 95,
    name: 'التين',
    transliteration: "At-Tin",
    totalVerses: 8,
    type: "meccan",
    image: [

      Assets.imagesQuranImages597,
    ],
  ),
  SurahDetails(
    id: 96,
    name: 'العلق',
    transliteration: "Al-Alaq",
    totalVerses: 19,
    type: "meccan",
    image: [
      Assets.imagesQuranImages597,

    ],
  ),
  SurahDetails(
    id: 97,
    name: 'القدر',
    transliteration: "Al-Qadr",
    totalVerses: 5,
    type: "meccan",
    image: [

      Assets.imagesQuranImages598,
    ],
  ),
  SurahDetails(
    id: 98,
    name: 'البينة',
    transliteration: "Al-Bayyina",
    totalVerses: 8,
    type: "medinan",
    image: [
      Assets.imagesQuranImages598,

      Assets.imagesQuranImages599,

    ],
  ),
  SurahDetails(
    id: 99,
    name: 'الزلزلة',
    transliteration: "Az-Zalzalah",
    totalVerses: 8,
    type: "medinan",
    image: [
      Assets.imagesQuranImages599,

    ],
  ),
  SurahDetails(
    id: 100,
    name: 'العاديات',
    transliteration: "Al-Adiyat",
    totalVerses: 11,
    type: "meccan",
    image: [
      Assets.imagesQuranImages599,

      Assets.imagesQuranImages600,

    ],
  ),
  SurahDetails(
    id: 101,
    name: 'القارعة',
    transliteration: "Al-Qari'a",
    totalVerses: 11,
    type: "meccan",
    image: [
      Assets.imagesQuranImages600,

    ],
  ),
  SurahDetails(
    id: 102,
    name: 'التكاثر',
    transliteration: "At-Takathur",
    totalVerses: 8,
    type: "meccan",
    image: [
      Assets.imagesQuranImages600,

    ],
  ),
  SurahDetails(
    id: 103,
    name: 'العصر',
    transliteration: "Al-Asr",
    totalVerses: 3,
    type: "meccan",
    image: [
      Assets.imagesQuranImages601,

    ],
  ),
  SurahDetails(
    id: 104,
    name: 'الهمزة',
    transliteration: "Al-Humazah",
    totalVerses: 9,
    type: "meccan",
    image: [
      Assets.imagesQuranImages601,

    ],
  ),
  SurahDetails(
    id: 105,
    name: 'الفيل',
    transliteration: "Al-Fil",
    totalVerses: 5,
    type: "meccan",
    image: [
      Assets.imagesQuranImages601,

    ],
  ),
  SurahDetails(
    id: 106,
    name: 'قريش',
    transliteration: "Quraish",
    totalVerses: 4,
    type: "meccan",
    image: [

      Assets.imagesQuranImages602,
    ],
  ),
  SurahDetails(
    id: 107,
    name: 'الماعون',
    transliteration: "Al-Ma'un",
    totalVerses: 7,
    type: "meccan",
    image: [
      Assets.imagesQuranImages602,

    ],
  ),
  SurahDetails(
    id: 108,
    name: 'الكوثر',
    transliteration: "Al-Kawthar",
    totalVerses: 3,
    type: "meccan",
    image: [
      Assets.imagesQuranImages602,

    ],
  ),
  SurahDetails(
    id: 109,
    name: 'الكافرون',
    transliteration: "Al-Kafirun",
    totalVerses: 6,
    type: "meccan",
    image: [

      Assets.imagesQuranImages603,
    ],
  ),
  SurahDetails(
    id: 110,
    name: 'النصر',
    transliteration: "An-Nasr",
    totalVerses: 3,
    type: "medinan",
    image: [
      Assets.imagesQuranImages603,

    ],
  ),
  SurahDetails(
    id: 111,
    name: 'المسد',
    transliteration: "Al-Masad",
    totalVerses: 5,
    type: "meccan",
    image: [
      Assets.imagesQuranImages603,

    ],
  ),
  SurahDetails(
    id: 112,
    name: 'الإخلاص',
    transliteration: "Al-Ikhlas",
    totalVerses: 4,
    type: "meccan",
    image: [

      Assets.imagesQuranImages604,
    ],
  ),
  SurahDetails(
    id: 113,
    name: 'الفلق',
    transliteration: "Al-Falaq",
    totalVerses: 5,
    type: "meccan",
    image: [
      Assets.imagesQuranImages604,

    ],
  ),
  SurahDetails(
    id: 114,
    name: 'الناس',
    transliteration: "An-Nas",
    totalVerses: 6,
    type: "meccan",
    image: [
      Assets.imagesQuranImages604,

    ],
  ),
];
